COMPILER_TYPE= gnu

CC=gcc

PROG=	midix
SRCS=	main.c speaker.c timer.c byebuffer.c

CCFLAGS= -Wall

DPADD+=	${LIBDRIVER} ${LIBSYS}
LDADD+=	-ldriver -lsys

LDFLAGS+= -L .

MAN=

BINDIR?= /usr/sbin

.include <bsd.prog.mk>
.include <bsd.gcc.mk>
